### ISSUE TITLE
Access to cURL info

### ISSUE THREAD

**Issue by patrickkusebauch** [dcarbone/soap-plus#8]
Hello, 
I am looking for a feature that is a deal breaker to me. I need to be able to profile the time it takes to complete a request. It seems everything is set up in this package except of one thing:

It calls cURL underneath. It creates a response in __doRequest implementing CurlPlusResponseInterface. This interface allows direct access to values in curl_getinfo.

HOWEVER. The response is not stored, just it's parts in debug properties. I am looking to a place (probably in the `_debugResults`) where to store the info, or better the whole Response object.

**Comment by dcarbone** [comment]
Sorry for the late reply!  As luck would have, I am actually in the middle of a small rewrite of CurlPlus that will make such things a much easier task.  I will be pushing new versions of both CurlPlus and SoapPlus later today, hopefully it will work for you!

**Comment by dcarbone** [comment]
@patrickkusebauch: OK, new version released.  Now the `_debugResults` array contains instances of the entire response object, meaning you can pull whatever values you wish out of there.

Let me know if this works for you!
